# Generated by Django 2.1.2 on 2018-10-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='caselist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xactno', models.CharField(max_length=200)),
                ('pltno', models.CharField(default='m', max_length=100)),
                ('car_tp', models.CharField(max_length=100)),
                ('vil_dt', models.DateTimeField(auto_now=True)),
                ('vil_tm', models.EmailField(blank=True, default='', max_length=100)),
                ('vil_add', models.CharField(blank=True, default='', max_length=200)),
                ('rule_1', models.TextField()),
                ('vildatetime', models.TextField(blank=True, default='')),
                ('vilinf', models.TextField(blank=True, default='')),
            ],
        ),
    ]
