# Generated by Django 2.1.2 on 2018-10-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_caselist'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('leader', models.CharField(max_length=200)),
                ('exp_dt', models.CharField(default='m', max_length=100)),
                ('exp_tm', models.CharField(max_length=100)),
                ('exp_op', models.CharField(max_length=100)),
                ('vilcnt', models.CharField(blank=True, default='', max_length=100)),
                ('piccnt', models.CharField(blank=True, default='', max_length=200)),
                ('vilrec', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='caselist',
            name='situa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='vil_dt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='vildatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
