# Generated by Django 2.1.2 on 2018-10-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20181009_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caselist',
            name='situa',
        ),
    ]
