# Generated by Django 2.1.2 on 2018-10-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_remove_caselist_situa'),
    ]

    operations = [
        migrations.CreateModel(
            name='casehistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xactno', models.CharField(max_length=200)),
                ('pltno', models.CharField(default='m', max_length=100)),
                ('car_tp', models.CharField(max_length=100)),
                ('vil_dt', models.CharField(max_length=100)),
                ('vil_tm', models.EmailField(blank=True, default='', max_length=100)),
                ('vil_add', models.CharField(blank=True, default='', max_length=200)),
                ('rule_1', models.TextField()),
                ('vildatetime', models.DateTimeField(auto_now=True)),
                ('vilinf', models.TextField(blank=True, default='')),
                ('situa', models.TextField(blank=True, default='')),
                ('piclink', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ourdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameQ', models.CharField(max_length=200)),
                ('passwordQ', models.CharField(max_length=200)),
                ('leader', models.CharField(max_length=200)),
                ('exp_dt', models.CharField(default='m', max_length=100)),
                ('exp_tm', models.CharField(max_length=100)),
                ('exp_op', models.CharField(max_length=100)),
                ('vilcnt', models.CharField(blank=True, default='', max_length=100)),
                ('piccnt', models.CharField(blank=True, default='', max_length=200)),
                ('vilrec', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='member',
        ),
        migrations.AddField(
            model_name='caselist',
            name='piclink',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='caselist',
            name='situa',
            field=models.TextField(blank=True, default=''),
        ),
    ]
