# Generated by Django 2.1.2 on 2018-10-10 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_auto_20181011_0448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ourdate',
        ),
    ]
