# Generated by Django 2.1.2 on 2018-10-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0006_delete_ourdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casehistory',
            old_name='car_tp',
            new_name='car_tph',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='piclink',
            new_name='piclinkh',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='pltno',
            new_name='pltnoh',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='rule_1',
            new_name='rule_1h',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='situa',
            new_name='situah',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='vil_add',
            new_name='vil_addh',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='vil_dt',
            new_name='vil_dth',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='vil_tm',
            new_name='vil_tmh',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='vildatetime',
            new_name='vildatetimeh',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='vilinf',
            new_name='vilinfh',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='xactno',
            new_name='xactnoh',
        ),
    ]
