# Generated by Django 2.1.2 on 2018-10-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_auto_20181011_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casehistory',
            old_name='car_tph',
            new_name='car_tp',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='piclinkh',
            new_name='piclink',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='pltnoh',
            new_name='pltno',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='rule_1h',
            new_name='rule_1',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='situah',
            new_name='situa',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='vil_addh',
            new_name='vil_add',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='vil_dth',
            new_name='vil_dt',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='vil_tmh',
            new_name='vil_tm',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='vildatetimeh',
            new_name='vildatetime',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='vilinfh',
            new_name='vilinf',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='xactnoh',
            new_name='xactno',
        ),
    ]
