# Generated by Django 2.1.2 on 2018-10-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0008_auto_20181011_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casehistory',
            old_name='situa',
            new_name='situa1',
        ),
    ]
